# @format

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run build --prod
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            sudo pip3 install awscli
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set default.region us-east-1
      - run:
          name: List files in directory
          command: ls dist/
      - run:
          name: Zip lambda file
          command: zip -q src/aws/lambda.zip src/aws/lambda.mjs
      - run:
          name: Deploy Lambda function
          command: |
            aws lambda update-function-code \
              --function-name header-lambda \
              --zip-file fileb://src/aws/lambda.zip
      # - run:
      #     name: Create IAM role for Lambda@Edge
      #     command: |
      #       ROLE_ARN=$(aws iam create-role --role-name CreateLambdaRole --assume-role-policy-document file://src/aws/assume-role-policy.json --query 'Role.Arn' --output text)
      #       aws iam attach-role-policy --role-name CreateLambdaRole --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      #       aws iam attach-role-policy --role-name CreateLambdaRole --policy-arn arn:aws:iam::aws:policy/service-role/AWSLambdaRole
      #       echo "export ROLE_ARN=$ROLE_ARN" >> $BASH_ENV
      - run:
          name: Update Lambda execution role
          command: |
            aws lambda update-function-configuration \
              --function-name header-lambda \
              --role $ROLE_ARN
      - run:
          name: Publish Lambda version
          command: |
            aws lambda publish-version \
              --function-name header-lambda
      - run:
          name: Get Lambda version ARN
          command: |
            LAMBDA_ARN=$(aws lambda list-versions-by-function \
              --function-name header-lambda \
              --query 'Versions[-1].FunctionArn' \
              --output text)
            echo "export LAMBDA_ARN=$LAMBDA_ARN" >> $BASH_ENV
      - run:
          name: Update CloudFront distribution behavior
          command: |
            # Replace <CLOUDFRONT_ID> with your CloudFront Distribution ID
            # Replace <BEHAVIOR_PATH_PATTERN> with the desired path pattern for the Cache Behavior
            aws cloudfront create-cloud-front-origin-access-identity \
              --cloud-front-origin-access-identity-config CallerReference=CircleCI,Comment=CircleCI
            aws cloudfront create-distribution \
              --distribution-config file://src/aws/cloudfront-distribution-config.json
            aws cloudfront update-distribution \
              --id E380M7BHVXFP6X \
              --if-match "$(aws cloud
