# @format

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run build --prod
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            sudo pip3 install awscli
      - run:
          name: Package Lambda function
          command: |
            zip -r lambda.zip dist/
      - run:
          name: Deploy Lambda function
          command: |
            aws lambda create-function \
              --function-name my-function-20230223 \
              --runtime nodejs14.x \
              --role arn:aws:iam::671249171349:user/CircleCi2
              --handler index.handler \
              --zip-file fileb://<(echo '
            exports.handler = async function(event) {
              console.log("Hello from Lambda!");
              return {
                statusCode: 200,
                body: "Success"
              };
            };
          ') \
          --region us-east-1
      - run:
          name: Sync directory with S3 bucket
          command: |
            aws s3 sync dist/circlecitest s3://circleciangularbucket --delete

workflows:
  version: 2
  build:
    jobs:
      - build
