version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.1
  node: circleci/node@4.7.0

jobs:
  build:
    docker:
      - image: circleci/node:16
    working_directory: ~/repo
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Build Angular App
          command: npm run build
      - aws-cli/setup
      - run:
          name: Install AWS SDK
          command: npm install aws-sdk
      # - run:
      #     name: Configure AWS CLI
      #     command: |
      #       aws configure set default.region us-east-1
      - run:
          name: Run deploy script
          command: |
            ./.circleci/deploy.sh
          environment:
            LAMBDA_FUNCTION_NAME: header-lambda
            CLOUDFRONT_DISTRIBUTION_ID: E380M7BHVXFP6X
            S3_BUCKET_NAME: circleciangularbucket

workflows:
  version: 2
  build:
    jobs:
      - build
