version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run:
          name: Build Angular App
          command: npm run build --prod
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            sudo pip3 install awscli
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set default.region us-east-1
      - run:
          name: List files in directory
          command: ls dist/
      - run:
          name: Run deploy script
          command: |
            chmod +x .circleci/deploy.mjs
            node .circleci/deploy.mjs

workflows:
  version: 2
  build:
    jobs:
      - build
