# @format

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run build --prod
      - run:
          name: Install AWS CLI
          command: |
            apk add --no-cache \
              py-pip \
              nodejs \
              curl
            pip install awscli
      - run: |
          aws s3 sync dist/ s3://circleciangularbucket --delete

workflows:
  version: 2
  build:
    jobs:
      - build
