# @format

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run build --prod
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            sudo pip3 install awscli
      - run:
          name: Package Lambda function
          command: |
            zip -r lambda.zip dist/
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set default.region us-east-1
      - run:
          name: List files in directory
          command: ls dist/
      - run:
          name: Deploy Lambda function
          command: |
            aws lambda create-function \
              --function-name my-function-20230223 \
              --runtime nodejs14.x \
              --role arn:aws:iam::671249171349:user/CircleCi2 \
              --handler index.handler \
              --code fileb://<(echo -n '
                const AWS = require("aws-sdk");
                exports.handler = async (event, context) => {
                  const s3 = new AWS.S3();
                  const params = {
                    Bucket: "my-bucket",
                    Key: "my-key",
                  };
                  const data = await s3.getObject(params).promise();
                  console.log("File content:", data.Body.toString());
                  return {
                    statusCode: 200,
                    body: "Success",
                  };
                };
              ' | base64)
      - run:
          name: Sync directory with S3 bucket
          command: |
            aws s3 sync dist/circlecitest s3://circleciangularbucket --delete

workflows:
  version: 2
  build:
    jobs:
      - build
