# @format

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run:
          name: Build Angular App
          command: npm run build --prod
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            sudo pip3 install awscli
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set default.region us-east-1
      - run:
          name: List files in directory
          command: ls dist/
      - run:
          name: Zip lambda file
          command: zip -q src/aws/lambda.zip src/aws/lambda.mjs
      - run:
          name: Deploy Lambda function
          command: |
            aws lambda update-function-code \
              --function-name header-lambda \
              --zip-file fileb://src/aws/lambda.zip
      - run:
          name: Wait for Lambda update to complete
          command: sleep 20
      - run:
          name: Publish Lambda version
          command: |
            LAMBDA_VERSION=$(aws lambda publish-version \
              --function-name header-lambda \
              --query Version \
              --output text)
            echo "export LAMBDA_VERSION=$LAMBDA_VERSION" >> $BASH_ENV
      - run:
          name: Run deploy script
          command: |
            chmod +x .circleci/deploy.sh
            ./.circleci/deploy.sh
      - run:
          name: Sync directory with S3 bucket
          command: |
            aws s3 sync dist/circlecitest s3://circleciangularbucket --delete

workflows:
  version: 2
  build:
    jobs:
      - build
