# @format

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update && sudo apt-get install -y awscli

workflows:
  version: 2
  build:
    jobs:
      - build
